### ISSUE TITLE
isOpen attribute

### ISSUE THREAD

**Issue by gibus27** [GuilhE/android-quantity-picker-view#1] opened 2020-03-27 12:46 UTC
Thanks a lot for your job !
I have a question about isOpen. I would like to use this picker always open. But when isOpen attribute is true, the start view is closed (only + button).
This attribute is private, then I cannot change it in my soft.
Is there any solution ?
Thank you again.
Alain

**Comment by GuilhE** [comment] 2020-03-27 12:56
Hello @gibus27 , nice catch!
Actually its open but not drawn that way. If you run your app and then touch the icon it will perform the close animation.

Note you'll need to:
`                    app:autoToggle="false"`
If your value == minValue (default is 0)

Let me take a look during the day and I'll fix it.

**Comment by GuilhE** [comment] 2020-03-27 20:32
Hello @gibus27 
I can't reproduce with the sample, can you?
What version are you using?

That attribute is private because the right way to open/close this view is:

1. By xml using `app:isOpen="true"`
2. `fun toggle(duration: Long = 500L)`
3. `fun toggle(duration: Long, interpolator: TimeInterpolator)`

The property `isOpen` has a `private set` for that purpose.

ps: forget my previous response, I was testing it wrong, it was a false positive 😅

**Comment by gibus27** [comment] 2020-03-28 06:25
I use the 1.2.2 released.
This is my widget description in XML :

<com.github.guilhe.views.QuantityPickerView
    android:id="@+id/pickDayOn"
    android:layout_width="130dp"
    android:layout_height="70dp"
    android:layout_gravity="start"
    android:layout_marginStart="100dp"
    android:layout_marginTop="80dp"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@+id/rubberTemp"
    app:max="95"
    app:min="0"
    app:textLabelSize="14sp"
    tools:isOpen="true"
    app:autoToggle="false"/>

As you can see in my screen capture, the couple of *quantity-picker* is
closed when I launch my application :
[image: image.png]
And when I use the toggle function with 500L, I obtain this (like a double
button) :
[image: image.png]

I would like to start my application like this :
[image: image.png]
What is the correct use to do it ?
Thank you.
Alain

**Comment by GuilhE** [comment] 2020-03-28 16:22
I can't see the images attached, but your layout has this:     `tools:isOpen="true"` you should not use `tools` because that will only affect preview. What you want is     `app:isOpen="true"`

**Comment by gibus27** [comment] 2020-03-28 16:38
Yes !
My trouble is *tools* switch *app* !
Now it's ok...
Sorry, it's my mistake !
Thanks you.
Alain

**Comment by GuilhE** [comment] 2020-03-28 17:18
Hey no problem :)
Happy coding!

**Closed as completed by GuilhE** 2020-03-28 17:18 UTC
Labels: question
